Public Enum headerEnum
    CSV_IDX_INSATSU_TYPE0 = 1                     '印刷種別:直接印刷
    CSV_IDX_INSATSU_TYPE1                         '印刷種別:PDF
    CSV_IDX_INSATSU_TYPE2                         '印刷種別:Excel
    CSV_IDX_INSATSU_TYPE3                         '印刷種別:CSV
    CSV_IDX_INSATSU_TYPE5                         '印刷種別:TSV
    CSV_IDX_SHUTSURYOKUSAKI1                      '出力先(PDF)
    CSV_IDX_SHUTSURYOKUSAKI2                      '出力先(Excel)
    CSV_IDX_SHUTSURYOKUSAKI3                      '出力先(CSV)
    CSV_IDX_SHUTSURYOKUSAKI5                      '出力先(TSV)
    CSV_IDX_SHUKKA_DATE                           '出荷日
    CSV_IDX_SEIDEN_NO                             '製伝No
    CSV_IDX_SHUKKA_LOT_NO                         '出荷ﾛｯﾄNo
    CSV_IDX_SHUKKA_SU                             '出荷数
    CSV_IDX_TORIHIKISAKI_CD                       '取引先ｺｰﾄﾞ
    CSV_IDX_FURIMUKESAKI_NAME                     '取引先略式名
    CSV_IDX_KC_HINMEI                             'KC品名
    CSV_IDX_KC_ZUBAN_JYUCHUZAN                    'KC図番
    CSV_IDX_KYAKUSAKI_PARTS_NO_JYUCHUZAN          '客先PN
    CSV_IDX_SPEC_JUCHUZAN                         'SPEC
    CSV_IDX_CHUMON_NO                             '注文番号
    CSV_IDX_HINMOKU_CD                            '品目ｺｰﾄﾞ
    CSV_IDX_SUB_CD                                'ｻﾌﾞｺｰﾄﾞ
    CSV_IDX_EIGYOSHO_CD                           '営業所ｺｰﾄﾞ
    CSV_IDX_ZAISHITSU_CD                          '材質ｺｰﾄﾞ
    CSV_IDX_CERAMIC                               'CERAMIC
    CSV_IDX_METALIZE                              'METALIZE
    CSV_IDX_METAL                                 'METAL
    CSV_IDX_PLATING                               'PLATING
    CSV_IDX_BIKO_1                                '備考1
    CSV_IDX_BIKO_2                                '備考2
    CSV_IDX_BIKO_3                                '備考3
    CSV_IDX_BIKO_4                                '備考4
    CSV_IDX_BIKO_5                                '備考5
    CSV_IDX_MEKKI_DATE                            'めっき日
    CSV_IDX_KENSAHYO_HAKKOSHA_NAME                '作成者名
    CSV_IDX_KENSAHYO_SHONINSHA_NAME               '承認者名
    CSV_IDX_SOGO_HANTEI                           '総合判定
    CSV_IDX_TAPE_LOT_NO                           'ﾃｰﾌﾟﾛｯﾄNo
    CSV_IDX_ABCLOT_NO                             'ABCﾛｯﾄNo
    CSV_IDX_YUKO_DATE                             '有効期限
    CSV_IDX_KENSAHYO_KENINSHA_NAME                '検印者名
    CSV_IDX_SAMPLING_PLAN1                        'SAMPLING_PLAN1
    CSV_IDX_SAMPLING_PLAN2                        'SAMPLING_PLAN2
    CSV_IDX_SAMPLING_PLAN3                        'SAMPLING_PLAN3
    CSV_IDX_SAMPLING_PLAN4                        'SAMPLING_PLAN4
    CSV_IDX_SAMPLING_PLAN5                        'SAMPLING_PLAN5
    CSV_IDX_HAKO_NO                               '箱番号(明細ｼｰｹﾝｽで代用)
    CSV_IDX_PROGRAM                               'PROGRAM
    CSV_IDX_MCO                                   'MCO
    CSV_IDX_MI                                    'MI
    CSV_IDX_CONFIG                                'CONFIG
    CSV_IDX_MS                                    'MS
    CSV_IDX_JIKI_CHECK_RANK                       '磁器ﾁｪｯｸﾗﾝｸ
    CSV_IDX_JIKI_CHECK_RANK_XTOP                  '磁器ﾁｪｯｸﾗﾝｸXTop
    CSV_IDX_JIKI_CHECK_RANK_XMIDDLE               '磁器ﾁｪｯｸﾗﾝｸXMiddle
    CSV_IDX_JIKI_CHECK_RANK_XBOTTOM               '磁器ﾁｪｯｸﾗﾝｸXBottom
    CSV_IDX_JIKI_CHECK_RANK_YRIGHT                '磁器ﾁｪｯｸﾗﾝｸYRight
    CSV_IDX_JIKI_CHECK_RANK_YMIDDLE               '磁器ﾁｪｯｸﾗﾝｸYMiddle
    CSV_IDX_JIKI_CHECK_RANK_YLEFT                 '磁器ﾁｪｯｸﾗﾝｸYLeft
    CSV_IDX_BUTSURYU_HASSO_DATE                   '物流発送日
    CSV_IDX_TORIHIKISAKI_SEISHIKI_NAME_JYUCHUZAN  '取引先名
End Enum